---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: headlamp-flux-test
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/kingdonb/headlamp-flux-test.git
  # secretRef:
  #   name: flux-readonly
