apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: test-yebyen
patches:
- path: headlamp-helmrelease.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: headlamp
- patch: |
    - op: add
      path: /spec/values/image
      value:
        registry: docker.io
        repository: kingdonb/headlamp
        pullPolicy: Always
        tag: "canary"
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: headlamp
- patch: |
    - op: add
      path: /spec/values/securityContext
      value:
        runAsUser: ~
        runAsGroup: ~
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: headlamp
