apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- path: headlamp-helmrelease.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: headlamp
    namespace: test-yebyen
- patch: |
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: headlamp
      namespace: test-yebyen
    values:
      securityContext:
        runAsUser: ~
        runAsGroup: ~
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: headlamp
    namespace: test-yebyen
